model:
  name: "MultilingualSER"
  input_shape: [128, 128, 1] 
  embedding_dim: 256
  hidden_layers:
    - type: "conv2d"
      filters: 64
      kernel_size: [3, 3]
      activation: "relu"
    - type: "conv2d"
      filters: 128
      kernel_size: [3, 3]
      activation: "relu"
    - type: "lstm"
      units: 128
      return_sequences: true
    - type: "dense"
      units: 64
      activation: "relu"
  output_layer:
    units: 5
    activation: "softmax"
