dataset:
  path:
    - "meta_csvs/en_RAVDESS.csv"

training:
  batch_size: 16
  num_epochs: 50
  patience: 15

optimizer:
  type: "Adam"
  lr: 0.001

loss:
  type: "CrossEntropyLoss"

model:
  name: "KuralNet"