dataset:
  path:
    - "/kaggle/input/ser-emouerj/emoUERJ"
    - "/kaggle/input/another-dataset/path"

training:
  batch_size: 16
  num_epochs: 50
  patience: 10

optimizer:
  type: "Adam"
  lr: 0.001

loss:
  type: "CrossEntropyLoss"

model:
  name: "FullEmotionClassifier"